services:
  web:
    build:
      context: .
    container_name: library_web
    ports:
      - "5656:5656"
    volumes:
      - .:/app  # Mount the code into the container
      - static_volume:/app/staticfiles
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:5656  # Ensure it runs in dev mode for auto-reload
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    container_name: library_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library_management
    ports:
      - "5435:5432"

  redis:
    image: redis:7
    container_name: library_redis
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
    container_name: library_celery
    command: celery -A library_management.celery worker --loglevel=info
    volumes:
      - .:/app  # Mount the code for Celery container as well (if needed)
    env_file:
      - .env
    depends_on:
      - redis
      - db

  celery-beat:
    build:
      context: .
    container_name: library_celery_beat
    command: celery -A library_management.celery beat --loglevel=info
    volumes:
      - .:/app  # Mount the code for Celery container as well
    env_file:
      - .env
    depends_on:
      - redis
      - db

volumes:
  static_volume:
